"""Launch and monitor the UR ROS 2 driver (ur_robot_driver) subprocess."""
from __future__ import annotations

import math
import os
import signal
import subprocess
import sys
import time
from pathlib import Path
from typing import List, Optional

from hyperfusion_ur3e import PKG_ROOT
from hyperfusion_ur3e.sidecar.config import load_yaml_config, DEFAULT_CONFIG
from hyperfusion_ur3e.urdf.mount_config import MountConfig
from hyperfusion_ur3e.urdf.tool_payload_config import ToolPayloadConfig

HW_JOINT_STATES_TOPIC = "/joint_states"
STAMPER_BIN = PKG_ROOT / "venv" / "bin" / "joint_states_stamper"
INITIAL_POSITIONS_PATH = PKG_ROOT / "config" / "initial_positions.yaml"
HYPERFUSION_RSP_LAUNCH = PKG_ROOT / "launch" / "hyperfusion_ur_rsp.launch.py"
HYPERFUSION_CONTROL_LAUNCH = PKG_ROOT / "launch" / "hyperfusion_ur_control.launch.py"
HYPERFUSION_CONTROLLERS_PATH = PKG_ROOT / "config" / "ur_controllers_hyperfusion.yaml"
KILL_STALE_SCRIPT = PKG_ROOT / "scripts" / "kill_stale_ur_ros.sh"

CANONICAL_JOINT_NAMES = [
    "shoulder_pan_joint",
    "shoulder_lift_joint",
    "elbow_joint",
    "wrist_1_joint",
    "wrist_2_joint",
    "wrist_3_joint",
]

STALE_PROCESS_PATTERNS = [
    "ur_control.launch.py",
    "hyperfusion_ur_control.launch.py",
    "hyperfusion_ur_rsp.launch.py",
    "venv/bin/joint_states_stamper",
    "/controller_manager/ros2_control_node",
    "/robot_state_publisher/robot_state_publisher",
    "/ur_robot_driver/dashboard_client",
    "/ur_robot_driver/controller_stopper_node",
    "/ur_robot_driver/urscript_interface",
    "/ur_robot_driver/trajectory_until_node",
    "/controller_manager/spawner",
]


class Ur3eRosDriverManager:
    """Starts ur_control.launch.py in a subprocess."""

    def __init__(
        self,
        *,
        ros_distro: str = "jazzy",
        ur_type: str = "ur3e",
        robot_ip: str = "192.168.0.10",
        reverse_ip: str = "0.0.0.0",
        use_mock_hardware: bool = True,
        initial_joint_deg: Optional[List[float]] = None,
        ceiling_mount: Optional[bool] = None,
        ceiling_mount_height_m: Optional[float] = None,
        mount_roll_deg: Optional[float] = None,
        mount_pitch_deg: Optional[float] = None,
        mount_yaw_deg: Optional[float] = None,
        mount_offset_x_mm: Optional[float] = None,
        mount_offset_y_mm: Optional[float] = None,
    ) -> None:
        sidecar_cfg = load_yaml_config(DEFAULT_CONFIG)
        self.ros_distro = ros_distro
        self.ur_type = ur_type
        self.robot_ip = robot_ip
        self.reverse_ip = reverse_ip.strip() or "0.0.0.0"
        self.use_mock_hardware = use_mock_hardware
        self.initial_joint_deg = initial_joint_deg or [0.0, -150.0, 120.0, 0.0, 90.0, 0.0]
        if ceiling_mount is None:
            ceiling_mount = bool(sidecar_cfg.get("ceiling_mount", True))
        if ceiling_mount_height_m is None:
            ceiling_mount_height_m = float(sidecar_cfg.get("ceiling_mount_height_m", 0.65))
        self.ceiling_mount = ceiling_mount
        self.ceiling_mount_height_m = ceiling_mount_height_m
        self.mount_config = MountConfig.from_cli(
            ceiling_mount_height_m=ceiling_mount_height_m,
            roll_deg=float(mount_roll_deg if mount_roll_deg is not None else sidecar_cfg.get("mount_roll_deg", 180.0)),
            pitch_deg=float(mount_pitch_deg if mount_pitch_deg is not None else sidecar_cfg.get("mount_pitch_deg", 0.0)),
            yaw_deg=float(mount_yaw_deg if mount_yaw_deg is not None else sidecar_cfg.get("mount_yaw_deg", 0.0)),
            offset_x_mm=float(
                mount_offset_x_mm if mount_offset_x_mm is not None else sidecar_cfg.get("mount_offset_x_mm", 0.0)
            ),
            offset_y_mm=float(
                mount_offset_y_mm if mount_offset_y_mm is not None else sidecar_cfg.get("mount_offset_y_mm", 0.0)
            ),
            ceiling_mount=ceiling_mount,
        )
        self.tool_payload_config = ToolPayloadConfig.from_env()
        self._process: Optional[subprocess.Popen] = None
        self._stamper_process: Optional[subprocess.Popen] = None

    @staticmethod
    def write_initial_positions_yaml(joint_deg: List[float]) -> None:
        """Write ros2_control mock initial pose (radians) for xacro."""
        if len(joint_deg) != 6:
            raise ValueError("initial_joint_deg must have 6 values.")

        INITIAL_POSITIONS_PATH.parent.mkdir(parents=True, exist_ok=True)
        lines: List[str] = [
            "# Generated by HyperFusion — mock-hardware startup pose (radians).\n",
        ]
        for name, deg in zip(CANONICAL_JOINT_NAMES, joint_deg):
            lines.append(f"{name}: {math.radians(float(deg)):.6f}\n")
        INITIAL_POSITIONS_PATH.write_text("".join(lines), encoding="utf-8")

    @property
    def running(self) -> bool:
        return self._process is not None and self._process.poll() is None

    def controller_manager_ready(self) -> bool:
        """True when ros2_control list_controllers succeeds."""
        try:
            self._verify_controller_manager(raise_on_failure=False)
            return True
        except Exception:
            return False

    def start(
        self,
        *,
        startup_timeout_s: float = 130.0,
        fail_fast_s: float = 15.0,
    ) -> None:
        if self.running:
            self._wait_for_controller_manager(startup_timeout_s)
            self.ensure_joint_states_stamper()
            return

        self.write_initial_positions_yaml(self.initial_joint_deg)
        self.stop_stale_launches()

        mock_flag = "true" if self.use_mock_hardware else "false"
        mock_sensor_flag = "true" if self.use_mock_hardware else "false"
        joint_controller = (
            "joint_trajectory_controller"
            if self.use_mock_hardware
            else "scaled_joint_trajectory_controller"
        )
        headless_flag = "true" if self.use_mock_hardware else "false"
        rsp_launch = HYPERFUSION_RSP_LAUNCH.as_posix()
        control_launch = HYPERFUSION_CONTROL_LAUNCH.as_posix()
        controllers_file = HYPERFUSION_CONTROLLERS_PATH.as_posix()
        pkg_root = PKG_ROOT.as_posix()
        payload_cfg = ToolPayloadConfig.from_env()
        payload_exports = payload_cfg.bash_exports()
        runtime_urdf = self._materialize_runtime_robot_description(payload_cfg)
        runtime_urdf_export = f"export HYPERFUSION_GENERATED_URDF='{runtime_urdf.as_posix()}' && "
        ros_env = (
            "export ROS_LOCALHOST_ONLY=1 && "
            "export RCUTILS_COLORIZED_OUTPUT=0 && "
            "export ROS2CLI_DISABLE_DAEMON=1 && "
        )
        launch_cmd = (
            f"export HYPERFUSION_UR3E_REPO='{pkg_root}' && "
            f"export HYPERFUSION_USE_MOCK_HARDWARE='{mock_flag}' && "
            f"export HYPERFUSION_MOCK_SENSOR_COMMANDS='{mock_sensor_flag}' && "
            f"{self.mount_config.bash_exports()}"
            f"{payload_exports}"
            f"{runtime_urdf_export}"
            f"{ros_env}"
            f"source /opt/ros/{self.ros_distro}/setup.bash && "
            f"ros2 launch '{control_launch}' "
            f"ur_type:={self.ur_type} "
            f"robot_ip:={self.robot_ip} "
            f"reverse_ip:={self.reverse_ip} "
            f"use_mock_hardware:={mock_flag} "
            f"mock_sensor_commands:={mock_sensor_flag} "
            f"description_launchfile:='{rsp_launch}' "
            f"controllers_file:='{controllers_file}' "
            f"initial_joint_controller:={joint_controller} "
            f"headless_mode:={headless_flag} "
            "launch_rviz:=false "
            "controller_spawner_timeout:=120"
        )
        if self.use_mock_hardware:
            sys.stderr.write(
                "UR3e driver: mock hardware enabled "
                f"(URDF GenericSystem, motion via {joint_controller}).\n"
            )
        else:
            sys.stderr.write(
                "UR3e driver: real robot, headless_mode=false "
                f"(External Control URCap), reverse_ip={self.reverse_ip}.\n"
            )

        self._process = subprocess.Popen(
            ["bash", "-lc", launch_cmd],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.PIPE,
            preexec_fn=os.setsid,
        )

        try:
            self._wait_for_process_start(fail_fast_s)
            self._wait_for_controller_manager(startup_timeout_s)
            self.ensure_joint_states_stamper()
        except Exception as exc:
            stderr_tail = self._read_stderr_tail(self._process) if self._process else ""
            self.stop()
            if stderr_tail and stderr_tail not in str(exc):
                raise RuntimeError(f"{exc}\n{stderr_tail}") from exc
            raise

    def _materialize_runtime_robot_description(self, cfg: ToolPayloadConfig) -> Path:
        from hyperfusion_ur3e.urdf.materialize_robot_description import (
            materialize_runtime_robot_description,
        )

        return materialize_runtime_robot_description(
            PKG_ROOT,
            ros_distro=self.ros_distro,
            ur_type=self.ur_type,
            robot_ip=self.robot_ip,
            reverse_ip=self.reverse_ip,
            use_mock_hardware=self.use_mock_hardware,
            headless_mode=self.use_mock_hardware,
            initial_positions_file=INITIAL_POSITIONS_PATH,
            cfg=cfg,
        )

    def schedule_tool_payload_probe(self) -> None:
        """Background check — must not block driver prestart / Connect enable."""
        import threading

        threading.Thread(
            target=self._log_tool_payload_in_driver_urdf,
            daemon=True,
            name="ur3e-tool-payload-probe",
        ).start()

    def _log_tool_payload_in_driver_urdf(self) -> None:
        from hyperfusion_ur3e.urdf.tool_payload_config import (
            ToolPayloadConfig,
            log_payload_probe_failure,
            probe_robot_state_publisher_payload,
        )

        cfg = ToolPayloadConfig.from_env()
        if not cfg.enabled:
            return
        if probe_robot_state_publisher_payload(
            self.ros_distro,
            cfg,
            retries=6,
            retry_delay_s=2.0,
        ):
            sys.stderr.write(
                "UR3e driver: tool payload in robot_description "
                f"({cfg.shape}, {cfg.radius_m * 1000.0:.0f} mm).\n"
            )
            return
        log_payload_probe_failure("driver robot_state_publisher", cfg)

    def ensure_joint_states_stamper(self, *, reset: bool = False) -> None:
        """Start hardware joint_states -> /joint_states republisher for MoveIt/RViz."""
        home_env = ",".join(str(float(v)) for v in self.initial_joint_deg)
        prev_env = os.environ.get("HYPERFUSION_HOME_JOINTS_DEG")
        os.environ["HYPERFUSION_HOME_JOINTS_DEG"] = home_env
        if reset or (prev_env is not None and prev_env != home_env and self._stamper_running()):
            self.stop_joint_states_stamper()

        if self._stamper_process is not None and self._stamper_process.poll() is None:
            return
        if self._stamper_running():
            return

        if not STAMPER_BIN.is_file():
            raise RuntimeError(
                f"joint_states_stamper not installed at {STAMPER_BIN}. "
                "Run ./install_env.sh in resources/ur3e."
            )

        stamper_cmd = (
            f"export ROS_LOCALHOST_ONLY=1 && "
            f"source /opt/ros/{self.ros_distro}/setup.bash && "
            f"exec {STAMPER_BIN.as_posix()}"
        )
        self._stamper_process = subprocess.Popen(
            ["bash", "-lc", stamper_cmd],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.PIPE,
            preexec_fn=os.setsid,
        )
        time.sleep(0.5)
        if self._stamper_process.poll() is not None:
            stderr_tail = self._read_stderr_tail(self._stamper_process)
            self._stamper_process = None
            detail = "joint_states_stamper exited during startup."
            if stderr_tail:
                detail = f"{detail}\n{stderr_tail}"
            raise RuntimeError(detail)

        sys.stderr.write(
            "UR3e driver: started joint_states_stamper "
            "(/joint_state_broadcaster/joint_states -> /joint_states, /joint_states_stamped)\n"
        )

    @staticmethod
    def ensure_joint_states_stamper_for_distro(
        ros_distro: str,
        *,
        home_joints_deg: Optional[List[float]] = None,
        reset: bool = False,
    ) -> None:
        """Ensure stamper is running when attaching to an external ur_control launch."""
        helper = Ur3eRosDriverManager(
            ros_distro=ros_distro,
            initial_joint_deg=list(home_joints_deg) if home_joints_deg is not None else None,
        )
        helper.ensure_joint_states_stamper(reset=reset)

    def stop(self) -> None:
        self.stop_joint_states_stamper()
        if self._process is None:
            return
        if self._process.poll() is None:
            try:
                os.killpg(os.getpgid(self._process.pid), signal.SIGTERM)
            except ProcessLookupError:
                pass
            try:
                self._process.wait(timeout=8.0)
            except subprocess.TimeoutExpired:
                try:
                    os.killpg(os.getpgid(self._process.pid), signal.SIGKILL)
                except ProcessLookupError:
                    pass
        self._process = None

    def stop_joint_states_stamper(self) -> None:
        if self._stamper_process is not None and self._stamper_process.poll() is None:
            try:
                os.killpg(os.getpgid(self._stamper_process.pid), signal.SIGTERM)
            except ProcessLookupError:
                pass
            try:
                self._stamper_process.wait(timeout=3.0)
            except subprocess.TimeoutExpired:
                try:
                    os.killpg(os.getpgid(self._stamper_process.pid), signal.SIGKILL)
                except ProcessLookupError:
                    pass
        self._stamper_process = None

    @staticmethod
    def _stamper_running() -> bool:
        proc = subprocess.run(
            ["pgrep", "-f", "venv/bin/joint_states_stamper"],
            capture_output=True,
            text=True,
        )
        return proc.returncode == 0

    @staticmethod
    def stop_stale_launches() -> None:
        """Terminate leftover UR ROS processes from prior partial launches."""
        try:
            if KILL_STALE_SCRIPT.is_file():
                subprocess.run(
                    ["bash", str(KILL_STALE_SCRIPT), "--keep-sidecar"],
                    check=False,
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                )
            else:
                for pattern in STALE_PROCESS_PATTERNS:
                    subprocess.run(
                        ["pkill", "-f", pattern],
                        check=False,
                        stdout=subprocess.DEVNULL,
                        stderr=subprocess.DEVNULL,
                    )
                time.sleep(1.0)
        except Exception:
            pass

    def _wait_for_process_start(self, fail_fast_s: float) -> None:
        fail_deadline = time.time() + fail_fast_s
        while time.time() < fail_deadline:
            self._raise_if_driver_stderr_fatal()
            if self._process is not None and self._process.poll() is not None:
                detail = f"UR driver exited during startup (code={self._process.returncode})."
                stderr_tail = self._read_stderr_tail(self._process)
                if stderr_tail:
                    detail = f"{detail}\n{stderr_tail}"
                raise RuntimeError(detail)
            time.sleep(0.25)

    def _wait_for_controller_manager(self, timeout_s: float) -> None:
        """Poll until ros2_control controllers are listed or timeout."""
        deadline = time.time() + max(5.0, timeout_s)
        attempt = 0
        while time.time() < deadline:
            self._raise_if_driver_stderr_fatal()
            if self._process is not None and self._process.poll() is not None:
                detail = f"UR driver exited during startup (code={self._process.returncode})."
                stderr_tail = self._read_stderr_tail(self._process)
                if stderr_tail:
                    detail = f"{detail}\n{stderr_tail}"
                raise RuntimeError(detail)

            if (
                not self.use_mock_hardware
                and attempt >= 2
                and self._script_sender_port_listening()
            ):
                sys.stderr.write(
                    "UR3e driver: port 50002 listening — press Play on External Control URCap "
                    f"(remote PC {self.reverse_ip}:50002).\n"
                )
                return

            if self._verify_controller_manager(raise_on_failure=False):
                if attempt > 0:
                    if self.use_mock_hardware:
                        sys.stderr.write(
                            f"UR3e driver: mock driver ready (joint_states) after {attempt} poll(s).\n"
                        )
                    else:
                        sys.stderr.write(
                            f"UR3e driver: controller manager ready after {attempt} poll(s).\n"
                        )
                return

            attempt += 1
            if attempt == 1:
                if self.use_mock_hardware:
                    sys.stderr.write(
                        "UR3e driver: waiting for mock driver (joint_states publishing, ~30s)…\n"
                    )
                else:
                    sys.stderr.write(
                        "UR3e driver: waiting for controller manager (may take up to ~2 min)…\n"
                    )
            elif attempt % 5 == 0:
                elapsed = int(timeout_s - max(0.0, deadline - time.time()))
                sys.stderr.write(f"UR3e driver: still waiting for controller manager ({elapsed}s)…\n")
            time.sleep(2.0)

        detail = "Timed out waiting for ros2_control controller manager."
        stderr_tail = self._read_stderr_tail(self._process) if self._process else ""
        if stderr_tail:
            detail = f"{detail}\n{stderr_tail}"
        raise RuntimeError(f"UR controller manager is not available.\n{detail}")

    def _raise_if_driver_stderr_fatal(self) -> None:
        """Fail fast when the driver subprocess logs a known fatal ROS error."""
        if self._process is None or self._process.stderr is None:
            return
        try:
            import select

            ready, _, _ = select.select([self._process.stderr], [], [], 0.0)
            if not ready:
                return
            chunk = self._process.stderr.read(8192)
        except Exception:
            return
        if not chunk:
            return
        text = chunk.decode("utf-8", errors="replace")
        if "undefined symbol" in text or "symbol lookup error" in text:
            raise RuntimeError(self._format_ros_abi_error(text))

    @staticmethod
    def _format_ros_abi_error(detail: str) -> str:
        hint = (
            "ROS 2 Jazzy UR packages are ABI-mismatched. In WSL run:\n"
            "  cd resources/ur3e && ./scripts/repair_ros_ur_packages.sh\n"
            "Or: sudo apt update && sudo apt install --only-upgrade "
            "ros-jazzy-ur-robot-driver ros-jazzy-ur-controllers ros-jazzy-ur-msgs "
            "ros-jazzy-controller-manager ros-jazzy-ros2-control ros-jazzy-ros2-controllers"
        )
        return f"UR driver failed during startup.\n{detail.strip()[-2000:]}\n{hint}"

    @staticmethod
    def _script_sender_port_listening() -> bool:
        """True when External Control script port (50002) is accepting connections."""
        try:
            proc = subprocess.run(
                ["bash", "-lc", "ss -tln | grep -q ':50002 '"],
                capture_output=True,
                timeout=3.0,
            )
            return proc.returncode == 0
        except Exception:
            return False

    def _mock_joint_states_available(self, *, topic_timeout_s: float = 4.0) -> bool:
        """Fallback readiness probe when ros2 control CLI is slow on WSL."""
        wait_s = max(1, int(topic_timeout_s))
        for topic in (
            "/joint_state_broadcaster/joint_states",
            "/joint_states",
        ):
            proc = subprocess.run(
                [
                    "bash",
                    "-lc",
                    f"export ROS_LOCALHOST_ONLY=1 ROS2CLI_DISABLE_DAEMON=1 && "
                    f"source /opt/ros/{self.ros_distro}/setup.bash && "
                    f"timeout {wait_s} ros2 topic hz {topic} --window 1 2>/dev/null | "
                    "head -1 | grep -q average",
                ],
                capture_output=True,
                text=True,
            )
            if proc.returncode == 0:
                return True
        return False

    def _verify_controller_manager(self, *, raise_on_failure: bool = True) -> bool:
        if self.use_mock_hardware:
            if self._mock_joint_states_available():
                return True
            if not raise_on_failure:
                return False
            raise RuntimeError(
                "UR mock driver: joint_states not publishing yet "
                "(check hyperfusion_ur_control.launch.py spawner in WSL logs)."
            )

        proc = subprocess.run(
            [
                "bash",
                "-lc",
                f"export ROS_LOCALHOST_ONLY=1 ROS2CLI_DISABLE_DAEMON=1 && "
                f"source /opt/ros/{self.ros_distro}/setup.bash && "
                "timeout 8 ros2 control list_controllers",
            ],
            capture_output=True,
            text=True,
        )
        output = proc.stdout or ""
        if proc.returncode == 0 and "joint_state_broadcaster" in output:
            joint_controller = (
                "joint_trajectory_controller"
                if self.use_mock_hardware
                else "scaled_joint_trajectory_controller"
            )
            for line in output.splitlines():
                if joint_controller in line and "active" in line:
                    return True
            if (
                joint_controller in output
                and self._script_sender_port_listening()
            ):
                sys.stderr.write(
                    "UR3e driver: controller manager up, port 50002 listening — "
                    "press Play on External Control URCap.\n"
                )
                return True
            if not raise_on_failure:
                return False
            raise RuntimeError(
                f"UR controller manager is up but {joint_controller} is not active.\n"
                f"{output.strip()[-2000:]}"
            )

        detail = (proc.stderr or output or "").strip()
        if "undefined symbol" in detail or "symbol lookup error" in detail:
            detail = self._format_ros_abi_error(detail)
        if not raise_on_failure:
            return False
        raise RuntimeError(f"UR controller manager is not available.\n{detail[-2000:]}")

    @staticmethod
    def _read_stderr_tail(process: subprocess.Popen) -> str:
        if process.stderr is None:
            return ""
        try:
            return process.stderr.read().decode("utf-8", errors="replace").strip()[-2000:]
        except Exception:
            return ""
